name: CLI Deploy
on:
  pull_request:
    paths:
      - packages/**
    branches:
      - main
    types:
      - closed
jobs:
  publish_when_merged:
    if: ${{ github.event.pull_request.merged == true && github.repository_owner == 'billybillydev' && contains(github.event.pull_request.labels.*.name,'cli') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.5.1

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
          node-version: 20
          cache: "pnpm"

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the package
        run: pnpm build:cli

      - name: Publish package
        shell: bash
        run: pnpm pub:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NODE_ENV: "production"
